"""initial

Revision ID: f80fda6d46f1
Revises: 
Create Date: 2026-03-20 00:49:06.825461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f80fda6d46f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reading_plan_day', 'reading_plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reading_plan_day', type_='foreignkey')
    # ### end Alembic commands ###
